### ISSUE TITLE
Regression: number of shares (Anteile) is parsed incorrectly if thousands separator is involved

### ISSUE THREAD

**Issue by egorlukomsky** [pytr-org/pytr#125]
After the recent refactoring, the number of shares (specifically `Anteile`) with thousands separator is parsed incorrectly.

`Anteile` seems to use `,` for decimal and `.` for thousands.
An example that breaks with the current code (should be 9400, comes out as 9.4):
```
"data": [
            {
              "title": "Anteile",
              "detail": {
                "text": "9.400",
                "trend": null,
                "action": null,
                "type": "text"
              },
              "style": "plain"
            },
...
]
```

Annoyingly, `Aktien` seems to use `.` as decimal separator:
```
"data": [
  {
    "title": "Aktien",
    "detail": {
      "text": "14.000000",
      "trend": null,
      "action": null,
      "type": "text"
    },
    "style": "plain"
  },
  ...
]
```

The parsing code [is shared](https://github.com/pytr-org/pytr/blob/b3e70bf05167b402d1629033bd458b35c6675c76/pytr/event.py#L201) currently, so either one, or the other will behave incorrectly and this method needs to be reworked a bit.

A quick fix would be to add another replace in-between:
```
re.sub(r"[^\,\.\d-]", "", unparsed_taxes_val).replace(
                    ".", ""
                ).replace(
                    ",", "."
                )
```
I prepared a PR, but then realized that `Aktien` has a different format, so I'll report it as a bug for today.

A couple more examples that don't break, but confirm the decimal separator for `Anteile`:
```
"data": [
  {
    "title": "Anteile",
    "detail": {
      "text": "50",
      "trend": null,
      "action": null,
      "type": "text"
    },
    "style": "plain"
  },
  ...
]

...

"data": [
  {
    "title": "Anteile",
    "detail": {
      "text": "5,928385",
      "trend": null,
      "action": null,
      "type": "text"
    },
    "style": "plain"
  },
  ...
]
```

_As a bonus, Python 3.12 throws a Warning for the regex strings: `SyntaxWarning: invalid escape sequence '\,'`. Converting it to a raw string fixes it:_ `re.sub(r"[^\,\.\d-]", "", elem_unparsed)`

**Comment by pinzutu** [comment]
Good catch! I observe the locale-specific formatting 'en' for the title 'Aktien', and 'de' for the titles 'Anteile', 'Gebühr', 'Steuer', 'Steuern'. Can you confirm this observation and that #126 works in your case?
