### ISSUE TITLE
last_days command seems to have no effect

### ISSUE THREAD

**Issue by V0xxel** [pytr-org/pytr#40]
Since I'm always getting a "BAD_REQUEST" error from the platform when executing dl_docs, I tried to limit the download to the last 5 days by using:

`pytr dl_docs --last_days 5 .`

This seems to have no effect for me. The download still starts at 01.06., which is where the first document was placed in my account.

EDIT: btw: the BAD_REQUEST seems to stem from the entry to verify your bank-account, so maybe it could be implemented to be skipped at the download

**Comment by marzzzello** [comment]
Is this error still occuring in the latest version?

**Comment by Akaame** [comment]
Confirmed that the `last_days` parameter indeed works.

```
pytr -V
0.1.9
```

**Comment by fredo-47** [comment]
Maybe there is confusion because the terminal log always shows all the documents (from all time) when pytr is executed. 

But only the documents from the timeframe given by `--last_days` parameter are actually saved to `PATH`.
So I guess it works as intended.
