### ISSUE TITLE
Export investments as CSV

### ISSUE THREAD

**Issue by LucEast** [pytr-org/pytr#60]
**Is your feature request related to a problem? Please describe.**

Da TradeRepublic nicht die beste Übersicht über die Investments bietet wollte ich 3rd Party Portfolio Tracker (Delta.app oder CoinTracking) nutzen um meine Investments (vorallem Crypto) dort übersichtlich einsehen zu können um Haltefristen etc. einhalten zu können.

**Describe the solution you'd like**

Eine weitere funktion wie z.B. export_investments wäre cool. Diese könnte ähnlich wie export_transactions aufgebaut sein, nur mit dem unterschied, dass nicht auf keywörter wie "`Einzahlung`", "`Bonuszahlungen`", "`Auszahlungen`" und "`Reinvestierung`" gematcht wird, sondern eventuell auf `event['cashChangeAmount']`.

**Describe alternatives you've considered**

-

**Additional context**

**Comment by LucEast** [comment]
Seems like this is already implemented within `pytr portfolio -o /path/to/output`
Unfortunately, the portfolio function runs in a deadlock for my portfolio. 
The issue is described in #61.
However, it would be nice if one could specify the CSV format which will be exported.

**Comment by Katzmann1983** [comment]
The issue with the deadlock is fixed now :D
