### ISSUE TITLE
Saveback documents are not downloaded

### ISSUE THREAD

**Issue by tjalb** [pytr-org/pytr#67]
**Description of the bug**
The documents related to the saveback are not downloaded.

I use the saveback  on a ETF savings plan. While the usual monthly transaction document is downloaded to "Sparplan/Abrechnung Ausführung" the transaction document for the separate investment of the saveback is missing. In addition in the transaction details in the TR-App there is an additional document "Kosteninformation" every month and with the first transaction of the saveback there is the "Activation" document.

**To Reproduce**

Ran the command `pytr dl_docs ./`

**Expected behavior**
All documents related to the saveback should be downloaded.

**Environment**
- OS: MacOS 13.6.7
- pytr version: 0.1.9

**Comment by Katzmann1983** [comment]
In the latest version is a folder 'Saveback'. Does this solve the issue?

**Comment by tjalb** [comment]
Yes, great, thank you!
