### ISSUE TITLE
release is not visible in package manager

### ISSUE THREAD

**Issue by kellerkind87** [pytr-org/pytr#88]
seems like the release is not pushed to the package manager:

https://github.com/pytr-org/pytr/actions/runs/9778738626/job/26996245800

**Comment by Katzmann1983** [comment]
Yeah, I really don't understand how that release process works. I did quite a lot of pushing, added a new yml file, changed there the password and thought it did not push anything. Then to my great surprise, pypi was updated to version 0.2.0
Any advice?

**Comment by kellerkind87** [comment]
- i am just reading the doc of the github action here https://github.com/pypa/gh-action-pypi-publish
- are the urls and secrets correct set in the github repo settings?

**Comment by Katzmann1983** [comment]
Ok, just tested again. The release creation works (now pytr 0.2.1 is available).
The error message asked to update the publish-pypi.yml
Did so. Let's see if it is fixed or broken :D
